version: "3"
services:
    db:
        image: mysql
        ports: 
            - "3306:3306"
        restart: always    
        environment:
            MYSQL_DATABASE: appledb
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_VERSION: latest
        volumes:
            - ./data/:/var/lib/mysql
            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
volumes:
    data:

        